name: Snapshot Build / 快照构建

on:
  push:
    branches:
      - main  # 假设您的主分支是 main

jobs:
  wheel-source-build:
    runs-on: ubuntu-latest

    steps:
    - name: 检查代码
      uses: actions/checkout@v4

    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build

    - name: 构建
      run: |
        python -m build --sdist --wheel

    - name: 上传 Artifact Wheel
      uses: actions/upload-artifact@v4
      with:
        name: aor-snapshot-wheel
        path: dist/*.whl

    - name: 上传 Artifact 源代码
      uses: actions/upload-artifact@v4
      with:
        name: aor-snapshot-source
        path: dist/*.tar.gz

  windows-build:
    runs-on: windows-latest

    steps:
    - name: 检查代码
      uses: actions/checkout@v4

    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel cx-freeze

    - name: 构建
      run: |
        python setup_excutable.py build

    - name: 上传 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aor-snapshot-windows
        path: build/exe.win-amd64-3.10
      
